### ISSUE TITLE
Don't show not init error in dev

### ISSUE THREAD

**Issue by driesvints** [facade/flare-client-js#64]
<img width="911" alt="Screenshot 2020-03-22 at 15 10 47" src="https://user-images.githubusercontent.com/594614/77251585-6f13b480-6c4f-11ea-82ce-0490a7404b85.png">

I know this error is meant to be informative but it's a bit annoying during development. Any possibility that this can be removed?

**Comment by AdrianMrn** [comment]
Hi @driesvints, thanks for your input! Because the plugin is built before the application it's used in, I don't think I can figure out whether it's in development mode or not.

I can now think of 2 possible solutions and I'd like your input on them, if you have a moment:
- Allow passing the `process.env.NODE_ENV` variable to the `flare.light()` call as an `applicationMode` parameter, which `flare-client-js` then uses to filter out these logs. eg `flare.light('key', process.env.NODE_ENV)`

or

- Add a `debug` option on the `flare.light` method (`flare.light('key', true)` or `false`) with default `false`, which disables all logs from the client.

I think I prefer the last one, maybe the client shouldn't be placing errors in the console by default, especially in a production environment.

**Comment by AdrianMrn** [comment]
I added a `debug` parameter to the `flare.light` method, that sets a `debug` property on the Flare client's class. It's `false` by default, and stops this kind of stuff from being logged (meaning you don't have to change anything in your code to stop getting the errors in your console).

You can upgrade to 1.0.6 to get this change.

**Comment by driesvints** [comment]
Awesome, thanks @AdrianMrn!
