### ISSUE TITLE
Reread docs

### ISSUE THREAD

**Issue by AdrianMrn** [facade/flare-client-js#76]
Make sure they're clear on all points

https://twitter.com/justenholter/status/1334694589039587328

**Comment by justenh** [comment]
Thanks for setting up this issue!

The main point of ambiguity stemmed from this ordered list...

![XZUQHRHD](https://user-images.githubusercontent.com/3868091/101177994-0e29e200-360e-11eb-9dcf-f401f20653c2.png)

This might just be me, but when I tried to integrate it, I felt that "Step 1" and "Step 2" seemed like a "this or that". If you're not in a React app, use "Step One", if you are, "Step Two"... The documentation being segmented into two pages, kind-of reinforced that feeling for me.

Additional, Step 5 "Add the your public" is ambiguous because it's covered in the "Step 1" for general errors, but isn't even mentioned in the React instructions. It wasn't until I realized that React apps require "Step 1" that I figured out where this belongs.

I think the clear thing to do is to make sure the React/Vue instructions clearly state the full process of integration, rather than relying on an additive style process of "Step 1" and "Step 2".

Hope that made sense. Thanks for the great service!

Also of note, I had our Laravel app up and running in under 2 minutes. It was amazing! I figured out the JS stuff in about 10-15 minutes, but I felt like I was sort of shooting from the hip rather than following a clearly outlined page of instructions.
